# 1. OrdinalEncoder

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\91636\\OneDrive\\Desktop\\Regex ML\\Data\\covid_toy.csv")

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df = df.drop(columns = ['age', 'fever'], axis=1)

In [5]:
df.head()

gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
df['gender'].value_counts()

Female    59
Male      41
Name: gender, dtype: int64

In [8]:
df['cough'].value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [9]:
df['city'].value_counts()

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [10]:
df['has_covid'].value_counts()

No     55
Yes    45
Name: has_covid, dtype: int64

In [11]:
oe = OrdinalEncoder(categories = [['Male','Female'],['Mild','Strong'],['Kolkata','Bangalore','Delhi','Mumbai'],['No','Yes']])

In [12]:
oe

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [15]:
oe.fit(df)

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [16]:
new_df = oe.transform(df)

In [17]:
new_df

array([[0., 0., 0., 0.],
       [0., 0., 2., 1.],
       [0., 0., 2., 0.],
       [1., 0., 0., 0.],
       [1., 0., 3., 0.],
       [1., 0., 1., 1.],
       [0., 1., 1., 0.],
       [1., 1., 3., 1.],
       [1., 1., 1., 0.],
       [1., 0., 2., 0.],
       [1., 0., 2., 0.],
       [1., 0., 3., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 2., 0.],
       [1., 0., 1., 1.],
       [1., 1., 1., 1.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 0., 2., 1.],
       [1., 1., 0., 0.],
       [0., 0., 3., 0.],
       [1., 0., 0., 1.],
       [1., 1., 2., 0.],
       [0., 0., 0., 0.],
       [1., 1., 3., 1.],
       [0., 0., 2., 1.],
       [0., 0., 0., 0.],
       [1., 1., 2., 1.],
       [1., 0., 0., 0.],
       [0., 0., 3., 1.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 2., 1.],
       [1., 0., 0., 0.],


In [16]:
df = pd.read_csv("C:\\Users\\91636\\OneDrive\\Desktop\\Regex ML\\Data\\tips.csv")

In [17]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
df =df.drop(columns = ['total_bill', 'tip', 'size'], axis=1)

In [19]:
df.head()

sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner
2    Male     No  Sun  Dinner
3    Male     No  Sun  Dinner
4  Female     No  Sun  Dinner

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
df['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [22]:
df['smoker'].value_counts()

No     151
Yes     93
Name: smoker, dtype: int64

In [23]:
df['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [24]:
df['time'].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [25]:
oe = OrdinalEncoder(categories=[['Male','Female'],['No','Yes'],['Sat','Sun','Thur','Fri'],['Dinner','Lunch']])

In [26]:
oe.fit(df)

OrdinalEncoder(categories=[['Male', 'Female'], ['No', 'Yes'],
                           ['Sat', 'Sun', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [27]:
new_df = oe.transform(df)

In [28]:
new_df = pd.DataFrame(new_df, columns = df.columns)

In [29]:
new_df

sex  smoker  day  time
0    1.0     0.0  1.0   0.0
1    0.0     0.0  1.0   0.0
2    0.0     0.0  1.0   0.0
3    0.0     0.0  1.0   0.0
4    1.0     0.0  1.0   0.0
..   ...     ...  ...   ...
239  0.0     0.0  0.0   0.0
240  1.0     1.0  0.0   0.0
241  0.0     1.0  0.0   0.0
242  0.0     0.0  0.0   0.0
243  1.0     0.0  2.0   0.0

[244 rows x 4 columns]

In [30]:
x = df.drop(columns = ['smoker'],axis=1)
y = df['smoker']

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# 2. get_dummies()

In [35]:
df = pd.read_csv("C:\\Users\\91636\\OneDrive\\Desktop\\Regex ML\\Data\\covid_toy.csv")

In [36]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [38]:
df = df.drop(columns=['age','fever'])

In [39]:
pd.get_dummies(df, columns = ['gender','cough','city'])

has_covid  gender_Female  gender_Male  cough_Mild  cough_Strong  \
0         No              0            1           1             0   
1        Yes              0            1           1             0   
2         No              0            1           1             0   
3         No              1            0           1             0   
4         No              1            0           1             0   
..       ...            ...          ...         ...           ...   
95        No              1            0           1             0   
96       Yes              1            0           0             1   
97        No              1            0           1             0   
98        No              1            0           0             1   
99       Yes              1            0           0             1   

    city_Bangalore  city_Delhi  city_Kolkata  city_Mumbai  
0                0           0             1            0  
1                0           1             0            0  
2                0           1             0            0  
3                0           0             1            0  
4                0           0             0            1  
..             ...         ...           ...          ...  
95               1           0             0            0  
96               0           0             1            0  
97               1           0             0            0  
98               0           0             0            1  
99               0           0             1            0  

[100 rows x 9 columns]

In [40]:
pd.get_dummies(df, columns = ['gender','cough', 'city'], drop_first=True)

has_covid  gender_Male  cough_Strong  city_Delhi  city_Kolkata  city_Mumbai
0         No            1             0           0             1            0
1        Yes            1             0           1             0            0
2         No            1             0           1             0            0
3         No            0             0           0             1            0
4         No            0             0           0             0            1
..       ...          ...           ...         ...           ...          ...
95        No            0             0           0             0            0
96       Yes            0             1           0             1            0
97        No            0             0           0             0            0
98        No            0             1           0             0            1
99       Yes            0             1           0             1            0

[100 rows x 6 columns]

# 3.  OneHot Encoder

In [41]:
from sklearn.preprocessing import OneHotEncoder

In [42]:
oe = OneHotEncoder(drop='first', sparse=False)

In [43]:
df.head(3)

gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes
2   Male  Mild    Delhi        No

In [44]:
df_new = oe.fit_transform(df[['gender','cough','city','has_covid']])

In [45]:
df_new

array([[1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [1.

In [46]:
df = pd.read_csv("C:\\Users\\91636\\OneDrive\\Desktop\\Regex ML\\Data\\tips.csv")

In [47]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [48]:
df = df.drop(columns = ['total_bill','tip','size'])

In [49]:
df.head()

sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner
2    Male     No  Sun  Dinner
3    Male     No  Sun  Dinner
4  Female     No  Sun  Dinner

In [50]:
from sklearn.preprocessing import OneHotEncoder

In [51]:
oe = OneHotEncoder(drop='first',sparse=False)

In [53]:
df_new = oe.fit_transform(df[['sex','smoker','day','time']])

In [56]:
df_new

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       ...,
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

# 4. LabelEncoder

In [57]:
df = pd.read_csv("C:\\Users\\91636\\OneDrive\\Desktop\\Regex ML\\Data\\covid_toy.csv")

In [58]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [59]:
df = df.drop(columns=['age','fever'])

In [60]:
from sklearn.preprocessing import LabelEncoder

In [61]:
lb = LabelEncoder()

In [62]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [63]:
new_df = pd.DataFrame(df,columns=df.columns)

In [64]:
new_df

gender  cough  city  has_covid
0        1      0     2          0
1        1      0     1          1
2        1      0     1          0
3        0      0     2          0
4        0      0     3          0
..     ...    ...   ...        ...
95       0      0     0          0
96       0      1     2          1
97       0      0     0          0
98       0      1     3          0
99       0      1     2          1

[100 rows x 4 columns]