# What is PowerTransformer in Machine Learning ?

In machine learning, the PowerTransformer in a type of data preprocessing technique used to transform the features of a daat to make them more Gaussina-like (more normally distributed).

# How I decide where I have to use Box-cox and where I have to use yeo-johnson ?

Box-Cox: The Box-Cox transformation is appropriate for non negative data that does not contain zero values. It assumes that the data follows a normal distribution and applies a power transformation to achive normality. The Box-Cox transformation is a more rigid transformation compared to the Yeo-Johnson transformation, because it requires the data to be strictly positive and cannot handle zero values.

Yeo-Johnson: The Yeo-Johnson transformation is a more flexible transformation that can be applied to both positive and negative data, including zero values. It also assumes that the data follows a normal distribution, but it applies

In [4]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

# Generate some random data with a skewed distribution 
data = np.random.gamma(1, 2, size=(100,1))

# Instantiate a PowerTransformer object
pt = PowerTransformer(method = 'yeo-johnson')

# Fit the PowerTransformer to the data and transform it
transformed_data = pt.fit_transform(data)

# Print the original and transformed data to compare
print('Original data:\n', data[:5])
print('Transformed data:\n', transformed_data[:5])

Original data:
 [[1.22427115]
 [3.80596999]
 [7.66016841]
 [2.26005453]
 [0.35486822]]
Transformed data:
 [[-0.34936739]
 [ 1.0316564 ]
 [ 2.09860974]
 [ 0.33384854]
 [-1.22914218]]


In [3]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

# Generate some random data with a skewed distribution 
data = np.random.gamma(1, 2, size=(100,1))

# Instantiate a PowerTransformer object
pt = PowerTransformer(method = 'box-cox')

# Fit the PowerTransformer to the data and transform it
transformed_data = pt.fit_transform(data)

# Print the original and transformed data to compare
print('Original data:\n', data[:5])
print('Transformed data:\n', transformed_data[:5])

Original data:
 [[0.01026004]
 [0.42886617]
 [3.50664043]
 [3.4747023 ]
 [4.57017164]]
Transformed data:
 [[-2.77327425]
 [-1.1934091 ]
 [ 0.96865453]
 [ 0.95576482]
 [ 1.35856607]]


In [5]:
import numpy as np
from sklearn.preprocessing import PowerTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Create a synthetic dataset
x = np.random.normal(loc=100, scale=10, size=(1000,5))
y = np.random.normal(loc=100, scale=10, size=1000)

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [8]:
# Fit and transform the sata using Box-Cox method
boxcox_transformer = PowerTransformer(method='box-cox', standardize=True)
x_train_bc = boxcox_transformer.fit_transform(x_train)
x_test_bc = boxcox_transformer.fit_transform(x_test)

# Fit and transform the sata using Yeo-Johnson method
yeojohnson_transformer = PowerTransformer(method='yeo-johnson', standardize=True)
x_train_yj = yeojohnson_transformer.fit_transform(x_train)
x_test_yj = yeojohnson_transformer.fit_transform(x_test)

In [ ]:
# Train a linear regression model using Box-Cox transformed data
